# Welcome to Jekyll!
#

# Site settings
title: SAU
description: |
  Bienvenido al Sistema de Ayuda Universitaria (SAU)
  Donde nos encargamos de resolver los problemas de la comunidad estudiantil dando un proceso a cada caso presentado sin omitir alguno <br>
  Todo estudiante debe alzar la voz no estas sola/o
owner: Sistema de Ayuda Universitaria # or company name
first_published: 2023 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  twitter:
  #github: 
  #linkedin-square: 
  facebook-official: https://www.facebook.com/CU.UAEMNEZA.OFICIAL?mibextid=ZbWKwL
  #google-plus-square: 
  email: sau_ayuda@uaemex.mx
  #flickr:
  instagram: https://instagram.com/cu.uaem.neza?igshid=MTNiYzNiMzkwZA==
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
